idf_component_register(
    SRCS
        "main.c"
        "media_publish.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        stream-video
        nvs_flash
        esp_wifi
        esp_netif
        esp_event
        esp_http_client
        esp_websocket_client
        mbedtls
        json
        esp_capture
        esp_video_codec
        esp_audio_codec
        esp_psram
)
