syntax = "proto3";

package stream.video.sfu.signal;

import "sfu.proto";
import "models.proto";

message SendAnswerRequest {
  stream.video.sfu.PeerType peer_type = 1;
  string sdp = 2;
  string session_id = 3;
}

message SendAnswerResponse {
  stream.video.sfu.models.Error error = 4;
}

message ICETrickle {
  stream.video.sfu.PeerType peer_type = 1;
  string ice_candidate = 2;
  string session_id = 3;
}

message ICETrickleResponse {
  stream.video.sfu.models.Error error = 4;
}

message SetPublisherRequest {
  string sdp = 1;
  string session_id = 2;
  repeated stream.video.sfu.models.TrackInfo tracks = 3;
}

message SetPublisherResponse {
  string sdp = 1;
  string session_id = 2;
  bool ice_restart = 3;
  stream.video.sfu.models.Error error = 4;
}
