syntax = "proto3";

package stream.video.sfu.signal;

import "sfu.proto";

message SendAnswerRequest {
  stream.video.sfu.PeerType peer_type = 1;
  string sdp = 2;
  string session_id = 3;
}

message SendAnswerResponse {
  string error_message = 1;
}

message ICETrickle {
  stream.video.sfu.PeerType peer_type = 1;
  string ice_candidate = 2;
  string session_id = 3;
}

message ICETrickleResponse {
  string error_message = 1;
}

message SetPublisherRequest {
  string sdp = 1;
  string session_id = 2;
}

message SetPublisherResponse {
  string sdp = 1;
  string session_id = 2;
  bool ice_restart = 3;
  string error_message = 4;
}
